[build]
  base = "/"
  publish = "public/"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.2"

[context.production]
  command = "hugo"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL/"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL/"